/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by MikuN2N tools/sync-native-version.ps1 before a native release build. */
#ifndef MIKUN2N_BUILD_VERSION_H
#define MIKUN2N_BUILD_VERSION_H
#define MIKUN2N_BUILD_VERSION "0.5.8-4"
#endif
