param([string]$PatchedSource = (Join-Path $PSScriptRoot '../native/n3n-3.4.4'))
$ErrorActionPreference = 'Stop'
[xml]$project = Get-Content (Join-Path $PSScriptRoot '../MikuN2N.csproj') -Raw
$properties = $project.Project.PropertyGroup | Where-Object { $_.BaseVersion }
$baseVersion = [string]$properties.BaseVersion
$buildNumber = [string]$properties.BuildNumber
if ($baseVersion -notmatch '^\d+\.\d+\.\d+$' -or $buildNumber -notmatch '^[1-9]\d*$') {
    throw 'BaseVersion and BuildNumber must form a numbered release.'
}
$version = "$baseVersion-$buildNumber"
if ($version.Length -gt 19) { throw 'The native peer version field supports at most 19 characters.' }
$sourceRoot = (Resolve-Path -LiteralPath $PatchedSource).Path
if (-not (Test-Path -LiteralPath (Join-Path $sourceRoot 'src/edge_utils.c'))) {
    throw 'PatchedSource must be the n3n source root.'
}
$header = @"
/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by MikuN2N tools/sync-native-version.ps1 before a native release build. */
#ifndef MIKUN2N_BUILD_VERSION_H
#define MIKUN2N_BUILD_VERSION_H
#define MIKUN2N_BUILD_VERSION "$version"
#endif
"@
[IO.File]::WriteAllText((Join-Path $sourceRoot 'src/mikun2n_build_version.h'), $header.Replace("`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Native build identity: $version"
